import type { Permission, Role, IAMUser } from "./types"

export const INITIAL_PERMISSIONS: Permission[] = [
  // Jobs Module
  {
    id: "perm-1",
    name: "Xem danh sách việc làm & JD",
    code: "jobs:read",
    description: "Cho phép xem danh sách việc làm và thông tin chi tiết mô tả công việc (JD).",
    category: "Jobs",
  },
  {
    id: "perm-2",
    name: "Thêm việc làm / Đồng bộ dữ liệu",
    code: "jobs:create",
    description: "Cho phép thêm mới việc làm hoặc chạy tiến trình đồng bộ dữ liệu cào về.",
    category: "Jobs",
  },
  {
    id: "perm-3",
    name: "Chỉnh sửa thông tin việc làm",
    code: "jobs:update",
    description: "Cho phép cập nhật thông tin mức lương, yêu cầu kỹ năng của tin việc làm.",
    category: "Jobs",
  },
  {
    id: "perm-4",
    name: "Xóa việc làm khỏi hệ thống",
    code: "jobs:delete",
    description: "Cho phép xóa bỏ tin việc làm hết hạn hoặc không hợp lệ.",
    category: "Jobs",
  },

  // CV Module
  {
    id: "perm-5",
    name: "Xem & Quản lý hồ sơ CV cá nhân",
    code: "cv:read_self",
    description: "Cho phép người dùng tải lên, xem và chỉnh sửa các phiên bản CV của chính mình.",
    category: "CV",
  },
  {
    id: "perm-6",
    name: "Phân tích mức độ phù hợp CV–JD",
    code: "cv:analyze",
    description: "Cho phép kích hoạt công cụ AI phân tích kỹ năng và gợi ý tối ưu CV.",
    category: "CV",
  },
  {
    id: "perm-7",
    name: "Xuất file CV định dạng PDF",
    code: "cv:export",
    description: "Cho phép tải xuống tài liệu CV tối ưu dưới định dạng PDF chất lượng cao.",
    category: "CV",
  },

  // Users Module
  {
    id: "perm-8",
    name: "Xem danh sách người dùng",
    code: "users:read",
    description: "Cho phép xem danh sách tài khoản người dùng và vai trò đang gán.",
    category: "Users",
  },
  {
    id: "perm-9",
    name: "Tạo tài khoản người dùng mới",
    code: "users:create",
    description: "Cho phép tạo mới tài khoản và cấu hình quyền truy cập.",
    category: "Users",
  },
  {
    id: "perm-10",
    name: "Gán vai trò & Phân quyền người dùng",
    code: "users:update_role",
    description: "Cho phép thay đổi vai trò hoặc gán thêm các quyền hạn tùy chỉnh cho người dùng.",
    category: "Users",
  },
  {
    id: "perm-11",
    name: "Xóa tài khoản người dùng",
    code: "users:delete",
    description: "Cho phép xóa tài khoản và thu hồi toàn bộ quyền truy cập.",
    category: "Users",
  },

  // System
  {
    id: "perm-12",
    name: "Quản trị toàn quyền hệ thống",
    code: "system:admin_all",
    description: "Toàn quyền quản trị hệ thống và cấu hình mọi tài nguyên.",
    category: "System",
  },
]

export const INITIAL_ROLES: Role[] = [
  {
    id: "role-1",
    name: "Super Admin",
    code: "super_admin",
    description: "Quản trị viên tối cao có toàn bộ quyền hạn trên hệ thống.",
    permissions: [
      "system:admin_all",
      "users:read",
      "users:create",
      "users:update_role",
      "users:delete",
      "jobs:read",
      "jobs:create",
      "jobs:update",
      "jobs:delete",
      "cv:read_self",
      "cv:analyze",
      "cv:export",
    ],
    userCount: 1,
    createdAt: "10/01/2026",
  },
  {
    id: "role-2",
    name: "Admin",
    code: "admin",
    description: "Quản trị viên quản lý tài khoản người dùng và đồng bộ dữ liệu việc làm.",
    permissions: [
      "users:read",
      "users:create",
      "users:update_role",
      "jobs:read",
      "jobs:create",
      "jobs:update",
      "cv:read_self",
      "cv:analyze",
      "cv:export",
    ],
    userCount: 2,
    createdAt: "15/01/2026",
  },
  {
    id: "role-3",
    name: "User",
    code: "user",
    description: "Người dùng ứng viên tìm kiếm việc làm, tối ưu CV và sử dụng Career Copilot.",
    permissions: [
      "jobs:read",
      "cv:read_self",
      "cv:analyze",
      "cv:export",
    ],
    userCount: 3,
    createdAt: "01/02/2026",
  },
]

export const INITIAL_IAM_USERS: IAMUser[] = [
  {
    id: "usr-1",
    userName: "admin.super",
    email: "admin@jobmatch.ai",
    path: "/",
    role: "Super Admin",
    customPermissions: ["system:admin_all"],
    consoleAccess: true,
    status: "Active",
    lastActivity: "Hôm nay",
    createdAt: "10/01/2026",
  },
  {
    id: "usr-2",
    userName: "tuannm",
    email: "tuannm@gmail.com",
    path: "/users/",
    role: "User",
    customPermissions: ["jobs:read", "cv:read_self", "cv:analyze", "cv:export"],
    consoleAccess: true,
    status: "Active",
    lastActivity: "25 ngày trước",
    createdAt: "15/02/2026",
  },
  {
    id: "usr-3",
    userName: "crawler.manager",
    email: "crawler@jobmatch.ai",
    path: "/services/",
    role: "Admin",
    customPermissions: ["jobs:read", "jobs:create", "jobs:update"],
    consoleAccess: false,
    status: "Active",
    lastActivity: "5 phút trước",
    createdAt: "01/03/2026",
  },
  {
    id: "usr-4",
    userName: "system.operator",
    email: "ops@jobmatch.ai",
    path: "/admins/",
    role: "Admin",
    customPermissions: ["users:read", "users:create", "users:update_role", "jobs:read", "jobs:create"],
    consoleAccess: true,
    status: "Active",
    lastActivity: "2 giờ trước",
    createdAt: "12/03/2026",
  },
  {
    id: "usr-5",
    userName: "linh.tran",
    email: "linhtran@gmail.com",
    path: "/users/",
    role: "User",
    customPermissions: ["jobs:read", "cv:read_self", "cv:analyze", "cv:export"],
    consoleAccess: true,
    status: "Active",
    lastActivity: "1 ngày trước",
    createdAt: "20/03/2026",
  },
  {
    id: "usr-6",
    userName: "hoang.nguyen",
    email: "hoangnguyen@gmail.com",
    path: "/users/",
    role: "User",
    customPermissions: ["jobs:read", "cv:read_self", "cv:analyze", "cv:export"],
    consoleAccess: true,
    status: "Active",
    lastActivity: "3 ngày trước",
    createdAt: "05/04/2026",
  },
]
